services:
  pipeline-dev:
    build: .
    entrypoint: [ sleep, infinity ]
    volumes:
      - ./src:/src
      - ./config:/config
      - ./job_defs:/job_defs
      - ./mock_data:/mock_data
      - ./inputs:/inputs
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    network_mode: "host"
