services:

  stac-fastapi-pgstac:
    container_name: stac-fastapi-pgstac
    image: ghcr.io/stac-utils/stac-fastapi-pgstac:4.0.3
    command: bash -c "python -m stac_fastapi.pgstac.app"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; response = urllib.request.urlopen('http://localhost:8888/_mgmt/ping'); exit(0 if b'PONG' in response.read() else 1)\""]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    env_file:
      - ./.env
    depends_on:
      pgstac:
        condition: service_healthy
    networks:
      - autoeval-net
    ports:
      - 8888:8888
      
  pgstac:
    container_name: pgstac
    image: ghcr.io/stac-utils/pgstac:v0.9.6
    volumes:
      - "./.data/pgstac:/var/lib/postgresql/data"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgstac -d postgis"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - autoeval-net


  asset-server:
    container_name: asset-server
    image: nginx:alpine
    volumes:
      - ./testdata/benchmark/assets:/usr/share/nginx/html:ro
    environment:
      - NGINX_PORT=8889
    command: |
      sh -c "sed -i 's/listen       80;/listen       8889;/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - autoeval-net
    ports:
      - 8889:8889

  nomad-server:
    build: ./local-nomad
    container_name: nomad-server
    privileged: true
    volumes:
      # Docker socket access required for Nomad to manage Docker containers as a task driver
      - /var/run/docker.sock:/var/run/docker.sock
      - ./local-nomad/nomad-server.hcl:/etc/nomad/nomad.hcl
      # preserver nomad state
      # this is only working if .data/nomad/data is created on host beforehand
      - ./.data/nomad:/nomad
      # cgroup filesystem access required for Nomad client to manage process isolation and resource limits
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/tmp
    environment:
      - NOMAD_ADDR=${NOMAD_ADDR}
    command: ["nomad", "agent", "-config", "/etc/nomad/nomad.hcl"]
    networks:
      - autoeval-net
    ports:
      - 4646:4646

networks:
  autoeval-net:
    driver: bridge
