services:
  autoeval-dev:
    build:
      context: .
      target: dev
    image: autoeval-dev:latest
    volumes:
      - ./src:/app/src
      - ./data:/data # for input/output data
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    entrypoint: [ sleep, infinity ]
    network_mode: host

  test-stac-fastapi-pgstac:
    container_name: test-stac-fastapi-pgstac
    image: ghcr.io/stac-utils/stac-fastapi-pgstac:4.0.3
    network_mode: host
    command: bash -c "python -m stac_fastapi.pgstac.app"
    env_file:
      - ./.env.docker
      
  test-pgstac:
    container_name: test-pgstac
    image: ghcr.io/stac-utils/pgstac:v0.9.6
    network_mode: host
    env_file:
      - ./.env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgstac -d postgis"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-asset-server:
    container_name: test-asset-server
    image: nginx:alpine
    network_mode: host
    volumes:
      - ./test/bench-data/assets:/usr/share/nginx/html:ro
    environment:
      - NGINX_PORT=8889
    command: |
      sh -c "sed -i 's/listen       80;/listen       8889;/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
